### ISSUE TITLE
Error on creating a new access filter

### ISSUE THREAD

**Issue by col-panic** [MEDEVIT/redmine_access_filters#2]
When creating a new access filter or editing the existing one via  the Redmine UI in

  Redmine version                4.2.8.stable
  Ruby version                   2.7.4-p191 (2021-07-07) [x86_64-linux-gnu]
  Rails version                  5.2.8.1

the following error code is shown in the log file

```
Completed 500 Internal Server Error in 15ms (ActiveRecord: 3.5ms)
  
ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError):
  
plugins/redmine_access_filters/app/controllers/access_filters_controller.rb:13:in `create'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

**Comment by col-panic** [comment]
When deleting a filter, the following error happens
```
Completed 500 Internal Server Error in 13ms (ActiveRecord: 3.7ms)
  
ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column access_filters.parent_id does not exist
LINE 1: ...CT "access_filters".* FROM "access_filters" WHERE "access_fi...
                                                             ^
: SELECT "access_filters".* FROM "access_filters" WHERE "access_filters"."parent_id" = $1):
  
plugins/redmine_access_filters/app/controllers/access_filters_controller.rb:38:in `destroy'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'

```
