### ISSUE TITLE
Fails with Redmine 5.1

### ISSUE THREAD

**Issue by col-panic** [MEDEVIT/redmine_access_filters#7]
Installing the plugin in Redmine 5.1 fails with 

```
mis-1  | LoadError: cannot load such file -- redmine_access_filters (LoadError)
mis-1  | <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
mis-1  | <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
mis-1  | /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
mis-1  | /usr/local/bundle/gems/zeitwerk-2.6.17/lib/zeitwerk/kernel.rb:34:in `require'
mis-1  | /usr/src/redmine/plugins/redmine_access_filters/init.rb:14:in `<top (required)>'
mis-1  | /usr/src/redmine/lib/redmine/plugin_loader.rb:31:in `load'
mis-1  | /usr/src/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'
mis-1  | /usr/src/redmine/lib/redmine/plugin_loader.rb:108:in `each'
mis-1  | /usr/src/redmine/lib/redmine/plugin_loader.rb:108:in `block in load'
mis-1  | /usr/local/bundle/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:427:in `instance_exec'
mis-1  | /usr/local/bundle/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:427:in `block in make_lambda'
mis-1  | /usr/local/bundle/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
mis-1  | /usr/local/bundle/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
mis-1  | /usr/local/bundle/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:603:in `catch'
mis-1  | /usr/local/bundle/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:603:in `block in default_terminator'
mis-1  | /usr/local/bundle/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:199:in `block in halting'
mis-1  | /usr/local/bundle/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:512:in `block in invoke_before'
mis-1  | /usr/local/bundle/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:512:in `each'
mis-1  | /usr/local/bundle/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:512:in `invoke_before'
mis-1  | /usr/local/bundle/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:105:in `run_callbacks'
mis-1  | /usr/local/bundle/gems/activesupport-6.1.7.8/lib/active_support/reloader.rb:88:in `prepare!'
mis-1  | /usr/local/bundle/gems/railties-6.1.7.8/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
mis-1  | /usr/local/bundle/gems/railties-6.1.7.8/lib/rails/initializable.rb:32:in `instance_exec'
mis-1  | /usr/local/bundle/gems/railties-6.1.7.8/lib/rails/initializable.rb:32:in `run'
mis-1  | /usr/local/bundle/gems/railties-6.1.7.8/lib/rails/initializable.rb:61:in `block in run_initializers'
mis-1  | /usr/local/bundle/gems/railties-6.1.7.8/lib/rails/initializable.rb:60:in `run_initializers'
mis-1  | /usr/local/bundle/gems/railties-6.1.7.8/lib/rails/application.rb:391:in `initialize!'
mis-1  | /usr/src/redmine/config/environment.rb:16:in `<top (required)>'
mis-1  | <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
mis-1  | <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
mis-1  | /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
mis-1  | /usr/local/bundle/gems/zeitwerk-2.6.17/lib/zeitwerk/kernel.rb:34:in `require'
mis-1  | /usr/local/bundle/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `block in require'
mis-1  | /usr/local/bundle/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:299:in `load_dependency'
mis-1  | /usr/local/bundle/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `require'
mis-1  | /usr/local/bundle/gems/railties-6.1.7.8/lib/rails/application.rb:367:in `require_environment!'
mis-1  | /usr/local/bundle/gems/railties-6.1.7.8/lib/rails/application.rb:533:in `block in run_tasks_blocks'
mis-1  | /usr/local/bundle/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
mis-1  | Tasks: TOP => db:migrate => db:load_config => environment
mis-1  | (See full trace by running task with --trace)
```

Tested against https://hub.docker.com/_/redmine

**Comment by nevenapajic98** [comment]
@col-panic
I fixed the issues and tested it. I uploaded the screenshots on upwork too.
![1](https://github.com/user-attachments/assets/a2cd6082-8c9b-4e43-87cf-6d82d4fcc7a0)
![2](https://github.com/user-attachments/assets/bb783df5-5702-4c23-8c52-216d4fe84c90)
![3](https://github.com/user-attachments/assets/2d0ef4df-4a08-4c31-8049-0ff1643d7aa2)
 Can you check it?

Nevena.

**Comment by col-panic** [comment]
@nevenapajic98 thank you - please provide a pull request so that I can check it with my installation!

**Comment by nevenapajic98** [comment]
@col-panic  Sure, Can you give me the offer on upwork?

**Comment by nevenapajic98** [comment]
@col-panic  I have not write permission for this repo. Can you give me permission?

**Comment by col-panic** [comment]
@nevenapajic98 unfortunately I already contracted someone else - I thought it was her commit - i did  not get a message in upwork and can't cancel the contract. Sorry. I'll keep you in the list to contact first for new tasks!

**Comment by nevenapajic98** [comment]
@col-panic Ok

**Comment by col-panic** [comment]
Fixed via https://github.com/MEDEVIT/redmine_access_filters/pull/8
